<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '7facf419ea43ec8afdd091de19739318' => $vendorDir . '/j7mbo/twitter-api-php/TwitterAPIExchange.php',
);
