<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'TwitterApi' => array($baseDir . '/vendor/twitter-api-php'),
);
